Fix for gating py27 job
Tests were failing with the following error:
"AttributeError: 'module' object has no attribute 'VIF_TYPE_IOVISOR"
Root cause of this issue was that we were cloning neutron master branch
in requirements.txt for gating/unit tests, and in master branch vendor
VIF_TYPE_* constants are removed from neutron codebase, hence the fix
uses stable/kilo branch to be used for unit/gating tests.

Closes-Bug: #1511351
Change-Id: I74778159b85799406af2ab12fbeed766199b806a